# Generated by Django 2.2.5 on 2023-08-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='comment_count',
            new_name='commentcount',
        ),
    ]
